---
title: "Lab 06 - Functions and iterations"
author: "Athos Rocha"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}

diamonds |> 
  filter(price < 600) |> 
  group_by(cut) |> 
  summarise(
    avg_carat = mean(carat, na.rm = TRUE),
    avg_price = mean(price, na.rm = TRUE)
  )

diamonds |> 
  filter(length_mm > 0 & width_mm > 0 & depth_mm > 0) |> 
  group_by(cut) |> 
  summarise(
    avg_carat = mean(carat, na.rm = TRUE),
    avg_volume = mean(length_mm*width_mm*depth_mm)
  )

diamonds |> 
  ggplot(aes(x = cut)) +
  geom_bar()

diamonds |> 
  filter()


```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?

diamonds |> 
  filter(!is.na(table_mm)) |> 
  summarise(
    avg_table_mm = mean(table_mm, na.rm = TRUE)
  )

# table_mm arithmetic mean within each clarity category

diamonds |> 
  group_by(clarity) |> 
  summarise(
    avg_table_mm = mean(table_mm, na.rm = TRUE)
  )

diamonds |> 
  group_by(clarity) |> 
  summarise(
    avg_table_mm = mean(table_mm, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = avg_table_mm, y = clarity)) +
  geom_col()






```

The better the clarity the lower the average table length and we can see this visualized with the graph above.

```{r}

diamonds |> 
  select(
    carat, depth_pct, table_pct, price, length_mm, width_mm, depth_mm, table_mm
  ) |> 
  summarise(
    across(where(is.numeric), \(x) mean(x))
  )
```

## Exercise 3

```{r}




```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input





# Copy your code from Ex 4 to test your new command





```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
